services:
  redis:
    image: redis:alpine
    command: [ "redis-server", "--bind", "redis", "--port", "6380" ]
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - ./data/redis:/data
    networks:
      django_network:

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      django_network:

  django:
    build: .
    container_name: django_app
    command:  >
      sh -c "./wait-for-it.sh postgres:5432 -- 
      python manage.py migrate --noinput && 
      python manage.py collectstatic --noinput && 
      daphne -b 0.0.0.0 -p 8000 winwisprr.asgi:application"
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/code
    environment:
      - REDIS_URL=redis://redis:6380/0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dbname
    env_file:
      - .env
    networks:
      django_network:
        ipv4_address: 172.16.238.10

networks:
  django_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
