services:
  django:
    build: .
    container_name: django_app
    command: daphne -b 0.0.0.0 -p 8000 winwisprr.asgi:application
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    volumes:
      - .:/code
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/dbname
    env_file:
      - .env

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dbname
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
