# Generated by Django 4.2.16 on 2024-10-14 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
